import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main overview and general docs
  overviewSidebar: [
    'overview',
    'README',
    'dependencies',
    'directory-structure',
    'glossary',
  ],

  // Foundations - Core architectural concepts
  foundationsSidebar: [{type: 'autogenerated', dirName: 'Foundations'}],

  // Data Model - Domain and data structures
  dataModelSidebar: [{type: 'autogenerated', dirName: 'Data-model'}],

  // Patterns - Development patterns and practices
  patternsSidebar: [{type: 'autogenerated', dirName: 'Patterns'}],

  // Frontend - Frontend architecture and components
  frontendSidebar: [{type: 'autogenerated', dirName: 'Frontend'}],

  // Quality - Testing, error handling, performance
  qualitySidebar: [{type: 'autogenerated', dirName: 'Quality'}],

  // Guides - Feature development guides
  guidesSidebar: [{type: 'autogenerated', dirName: 'Guides'}],

  // Operations - Deployment and operational concerns
  operationsSidebar: [{type: 'autogenerated', dirName: 'Operations'}],
};

export default sidebars;
